spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost/work"
    username: "root"
    password: "Chan1234!"
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true

  #  sql:
  #    init:
  #      mode: always

  jackson:
    default-property-inclusion: non_null
